name: CI pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: chmod +x scripts/*.sh && ./scripts/build.sh

      - name: Run Container
        run: chmod +x scripts/*.sh && ./scripts/start.sh

      - name: Run health script 
        run: |
          chmod +x scripts/*.sh
          ./scripts/health-check.sh || true
